services:
  - type: web
    name: book-search-mern
    env: node
    buildCommand: npm run render-build
    startCommand: npm start
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
    healthCheckPath: /graphql
