services:
  - type: web
    name: book-search-mern
    env: node
    buildCommand: cd /opt/render/project/repo && npm run render-build
    startCommand: cd /opt/render/project/repo && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
    healthCheckPath: /graphql
